---
name: Build PDF with LaTeX

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Run Python script
        run: python ebooks/md-to-tex.py .  

      - name: Copy generated files
        run: |
          cp ebooks/cover.jpg ebooks/wisdom.tex ebooks/wisdom.md.tex .

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: wisdom.tex
          latexmk_use_xelatex: true
          
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: wisdom.pdf

