---
name: Build PDF with LaTeX

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Markdown to TeX
        uses: actions/setup-python@v1
        run: |
          python ./ebooks/md-to-tex.py .
          cp ebooks/cover.jpg ebooks/wisdom.md.tex ebooks/wisdom.tex .
      - name: Generate PDF document
        uses: hspaans/latexmk-action@v2.1.0
        with:
          format: pdf
          filename: wisdom.tex
          options: -xelatex
name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run Python script
        run: python ebooks/md-to-tex.py .  

      - name: Copy generated files
        run: |
          cp ebooks/cover.jpg ebooks/wisdom.tex ebooks/wisdom.md.tex .

      - name: Install TeX Live
        run: sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-fonts-extra

      - name: Run XeLaTeX
        run: |
          xelatex -pdf wisdom.tex

